# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:stretch
    environment:
      GO111MODULE: on
    working_directory: /go/src/github.com/DCSO/fever
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: 'sudo apt-get update && sudo apt-get install redis-server -y'
      - run: go get -v -t -d ./...
      - run: go test -v ./...
